-- MAGACIN UPDATE
alter table if exists magacin
add column if not exists parent_rola_id bigint,
add column if not exists operacija text;

-- FORMATIRANJE
create table if not exists planovi_formatiranja (
 id bigint generated by default as identity primary key,
 nalog_id bigint,
 rola_ulaz bigint,
 plan text,
 created_at timestamp default now()
);

-- REZANJE
create table if not exists planovi_rezanja (
 id bigint generated by default as identity primary key,
 nalog_id bigint,
 plan text,
 created_at timestamp default now()
);

-- UCINAK
create table if not exists radni_ucinak (
 id bigint generated by default as identity primary key,
 nalog_id bigint,
 rola_id bigint,
 radnik text,
 operacija text,
 pocetak timestamp,
 kraj timestamp,
 trajanje_min numeric,
 kolicina numeric,
 ucinak numeric
);
