create table if not exists planovi_secenja (
  id bigint generated by default as identity primary key,
  created_at timestamp default now(),
  rola_id bigint,
  broj_rolne text,
  lokacija text,
  lot text,
  plan text,
  otpad_mm integer
);

alter table planovi_secenja enable row level security;

create policy "allow_all" on planovi_secenja
for all to anon, authenticated
using (true) with check (true);
